name: schedule

on:
  push:
    branches: [run-action]

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-renv@v2
      
      - name: FPL Code
        run : Rscript -e 'source("FPL_API.R")'
